name: Update index & Deploy Pages

on:
  push:
    branches: ["main"]
    paths:
      - "documenti/**"
      - "scripts/**"
      - "templates/**"
      - "index.html"
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate manifest + update HTML
        run: |
          python scripts/update_index.py \
            --root documenti/cartella_con_documenti \
            --index index.html \
            --base-url "/documenti/cartella_con_documenti" \
            --manifest data/manifest.json

      - name: Commit updated HTML/manifest if changed
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add index.html data/manifest.json || true
          if git diff --cached --quiet; then
            echo "No HTML changes"
          else
            git commit -m "chore(site): auto-update index"
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
